# Generated by Django 2.2.2 on 2019-06-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusGo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=20)),
                ('go_station_id', models.CharField(max_length=20)),
                ('go_route_id', models.CharField(max_length=20)),
                ('go_station_order', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='BusOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=20)),
                ('out_station_id', models.CharField(max_length=20)),
                ('out_route_id', models.CharField(max_length=20)),
                ('out_station_order', models.CharField(max_length=5)),
            ],
        ),
    ]
